import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useReducer, useState } from 'react';
import PageWithFooter from '../components/generic/PageWithFooter';
import Hero from '../components/Hero';
import ProjectFilters from '../components/ProjectFilters';
import ProjectThumbnail from '../components/ProjectThumbnail';
import categories from '../data/categories';
import projects from '../data/projects';

export interface FiltersState {
  [key: string]: boolean;
}

const initialState: FiltersState = {
  all: true,
};
categories.forEach((c) => {
  initialState[c.id] = false;
});

const reducer = (state: FiltersState, action: { type: string; id: string }) => {
  switch (action.type) {
    case 'toggle':
      if (action.id === 'all') {
        const newState: { [key: string]: boolean } = {};

        for (const property in state) {
          newState[property] = false;
        }
        newState.all = true;

        return newState;
      } else {
        return {
          ...state,
          all:
            Object.keys(state).filter(
              (k: string) => k !== 'all' && k !== action.id && state[k]
            ).length === 0 && state[action.id]
              ? true
              : false,
          [action.id]: !state[action.id],
        };
      }
    default:
      throw new Error();
  }
};

const Home: NextPage = () => {
  const [state, dispatch] = useReducer(reducer, initialState);
  const [filteredProjects, setFilteredProjects] = useState(projects);
  useEffect(() => {
    setFilteredProjects(() => {
      if (state.all) {
        return projects;
      } else {
        return projects.filter((p) => p.categories.find((c) => state[c]));
      }
    });
  }, [state]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWithFooter>
        <main>
          <Hero />
          <div
            style={{
              paddingTop: '124px',
              paddingBottom: '108px',
              paddingLeft: '64px',
              paddingRight: '64px',
              color: 'white',
              background:
                'linear-gradient(150deg, rgba(102,108,101,1) 0%, rgba(80,88,79,1) 100%)',
            }}
          >
            <div
              style={{
                margin: 'auto',

                maxWidth: '1260px',
              }}
            >
              <h2 style={{ marginBottom: '72px' }}>
                Select a project to get started.
              </h2>
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'auto 220px',
                  columnGap: '72px',
                }}
              >
                <div
                  style={{
                    display: 'grid',
                    columnGap: '44px',
                    rowGap: '44px',
                    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
                  }}
                >
                  {filteredProjects.map((p) => (
                    <ProjectThumbnail
                      key={p.slug}
                      href={`/projects/${p.slug}`}
                      title={p.title}
                      imageSrc={p.thumbnail.src}
                    />
                  ))}
                </div>
                <ProjectFilters state={state} dispatch={dispatch} />
              </div>
            </div>
          </div>
        </main>
        <footer style={{ background: '#202120', color: 'white' }}>Derp</footer>
      </PageWithFooter>
    </>
  );
};

export default Home;
