import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import BackgroundImage from '../components/generic/BackgroundImage';
import PageWithFooter from '../components/generic/PageWithFooter';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWithFooter>
        <main>
          <Hero />
          <div
            style={{
              paddingTop: '108px',
              paddingBottom: '108px',
              paddingLeft: '64px',
              paddingRight: '64px',
              color: 'white',
              background:
                'linear-gradient(150deg, rgba(102,108,101,1) 0%, rgba(80,88,79,1) 100%);',
            }}
          >
            <div
              style={{
                margin: 'auto',
                // maxWidth: '1280px',
              }}
            >
              <h2>Select a project to get started.</h2>
            </div>
          </div>
        </main>
        <footer style={{ background: '#202120', color: 'white' }}>Derp</footer>
      </PageWithFooter>
    </>
  );
};

export default Home;
