import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Checkbox from '../components/Checkbox';
import BackgroundImage from '../components/generic/BackgroundImage';
import PageWithFooter from '../components/generic/PageWithFooter';
import Hero from '../components/Hero';
import ProjectFilters from '../components/ProjectFilters';
import ProjectThumbnail from '../components/ProjectThumbnail';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWithFooter>
        <main>
          <Hero />
          <div
            style={{
              paddingTop: '124px',
              paddingBottom: '108px',
              paddingLeft: '64px',
              paddingRight: '64px',
              color: 'white',
              background:
                'linear-gradient(150deg, rgba(102,108,101,1) 0%, rgba(80,88,79,1) 100%);',
            }}
          >
            <div
              style={{
                margin: 'auto',

                maxWidth: '1260px',
              }}
            >
              <h2 style={{ marginBottom: '72px' }}>
                Select a project to get started.
              </h2>
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'auto 220px',
                  columnGap: '72px',
                }}
              >
                <div
                  style={{
                    display: 'grid',
                    columnGap: '44px',
                    rowGap: '44px',
                    gridTemplateColumns: 'auto auto auto',
                    // gridTemplateRows: '280px',
                  }}
                >
                  <ProjectThumbnail
                    title="Easy Woven Cane Nightstand"
                    imageSrc="/images/framed-board.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Live Edge Coffee Table"
                    imageSrc="/images/angled-board.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Concrete Coffee Table (With Cooler & Firepit)!"
                    imageSrc="/images/little-house.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Easy Woven Cane Nightstand"
                    imageSrc="/images/og-board.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Easy Woven Cane Nightstand"
                    imageSrc="/images/monitor-stand.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Easy Woven Cane Nightstand"
                    imageSrc="/images/framed-board.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                  <ProjectThumbnail
                    title="Easy Woven Cane Nightstand"
                    imageSrc="/images/tv-stand.jpg"
                    style={
                      {
                        // width: '33%',
                      }
                    }
                  />
                </div>
                <ProjectFilters />
              </div>
            </div>
          </div>
        </main>
        <footer style={{ background: '#202120', color: 'white' }}>Derp</footer>
      </PageWithFooter>
    </>
  );
};

export default Home;
